FROM python:3.10-slim

WORKDIR /app

COPY src/ .

COPY Pipfile Pipfile.lock /app/

RUN pip install pipenv

RUN pipenv install --deploy --system --ignore-pipfile

EXPOSE 5000

ENV FLASK_APP=main.py
ENV FLASK_RUN_HOST=0.0.0.0

CMD ["flask", "run"]